# library(shiny)
#
# library(shinydashboard)
# library(d3heatmap)
# # ls()
# library(pcaExplorer)
# # example(pcaExplorer)
# library(DESeq2)
# library(ggplot2)
# library(shinyAce)
# library(DT)
# library(knitr)
# library(rmarkdown)
# library(pheatmap)
